name: ai_interview_coach_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  go_router: ^16.2.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.1
  font_awesome_flutter: ^10.9.1
  supabase_flutter: ^2.10.0
  get_it: ^8.2.0
  google_sign_in: ^7.1.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_spinkit: ^5.2.2
  image_picker: ^1.2.0
  toastification: ^3.0.3
  animated_digit: ^3.3.1+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: app_assets.dart
  ignore_comments: true
  field_prefix:
  classname: AppAssets
